defmodule TragarAi.Repo.Migrations.EphemeralInteractions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      remove :final_answer
      remove :draft_answer
      remove :tool_log
      remove :facts
    end
  end

  def down do
    alter table(:interactions) do
      add :facts, :map, default: %{}
      add :tool_log, {:array, :map}, default: []
      add :draft_answer, :text
      add :final_answer, :text
    end
  end
end
