defmodule TragarAi.Repo.Migrations.AddInteractionTicketTiming do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      add :ticket_id, :text
      add :duration_ms, :bigint
    end
  end

  def down do
    alter table(:interactions) do
      remove :duration_ms
      remove :ticket_id
    end
  end
end
