defmodule TragarAi.Repo.Migrations.AddLogisticsCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shipments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :waybill_number, :text, null: false
      add :account_reference, :text
      add :shipper_reference, :text
      add :service_type, :text
      add :status_code, :text
      add :status_description, :text
      add :consignor_name, :text
      add :consignee_name, :text
      add :consignee_city, :text
      add :tracking_events, {:array, :map}, default: []
      add :pod, :map
      add :raw, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:shipments, [:waybill_number], name: "shipments_unique_waybill_index")

    create table(:quotes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quote_number, :text, null: false
      add :quote_obj, :text
      add :account_reference, :text
      add :service_type, :text
      add :status_code, :text
      add :status_description, :text
      add :consignor_name, :text
      add :consignee_name, :text
      add :charged_amount, :text
      add :items, {:array, :map}, default: []
      add :sundries, {:array, :map}, default: []
      add :raw, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:quotes, [:quote_number], name: "quotes_unique_quote_index")
  end

  def down do
    drop_if_exists unique_index(:quotes, [:quote_number], name: "quotes_unique_quote_index")

    drop table(:quotes)

    drop_if_exists unique_index(:shipments, [:waybill_number],
                     name: "shipments_unique_waybill_index"
                   )

    drop table(:shipments)
  end
end
