defmodule TragarAi.Repo.Migrations.AddPartyDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vehicles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :registration, :text, null: false
      add :status, :text
      add :available, :boolean
      add :description, :text
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:vehicles, [:registration], name: "vehicles_unique_registration_index")

    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ticket_id, :text, null: false
      add :subject, :text
      add :status, :text
      add :priority, :text
      add :requester_email, :text
      add :account_reference, :text
      add :updated_at_source, :text
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tickets, [:ticket_id], name: "tickets_unique_ticket_index")

    create table(:invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :invoice_number, :text, null: false
      add :account_reference, :text
      add :amount, :text
      add :balance, :text
      add :status, :text
      add :invoice_date, :text
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:invoices, [:invoice_number], name: "invoices_unique_invoice_index")

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_reference, :text, null: false
      add :name, :text
      add :email, :text
      add :description, :text
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
      add :cached_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:account_reference], name: "customers_unique_account_index")
  end

  def down do
    drop_if_exists unique_index(:customers, [:account_reference],
                     name: "customers_unique_account_index"
                   )

    drop table(:customers)

    drop_if_exists unique_index(:invoices, [:invoice_number],
                     name: "invoices_unique_invoice_index"
                   )

    drop table(:invoices)

    drop_if_exists unique_index(:tickets, [:ticket_id], name: "tickets_unique_ticket_index")

    drop table(:tickets)

    drop_if_exists unique_index(:vehicles, [:registration],
                     name: "vehicles_unique_registration_index"
                   )

    drop table(:vehicles)
  end
end
