defmodule TragarAi.Repo.Migrations.TicketReceivedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :waybill_reference, :text
      add :received_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:tickets) do
      remove :received_at
      remove :waybill_reference
    end
  end
end
