defmodule TragarAi.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:interactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :question, :text, null: false
      add :intent, :text
      add :entities, :map, default: %{}
      add :facts, :map, default: %{}
      add :source, :text
      add :draft_answer, :text
      add :final_answer, :text
      add :status, :text, null: false, default: "drafted"
      add :error, :text
      add :agent, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:interactions)
  end
end
