defmodule TragarAi.Repo.Migrations.InteractionToolLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      add :tool_log, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:interactions) do
      remove :tool_log
    end
  end
end
