defmodule TragarAi.Repo.Migrations.CreateQuoteSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quote_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ticket_id, :text, null: false
      add :account_reference, :text, null: false
      add :requester_email, :text
      add :status, :text, default: "collecting"
      add :slots, :map, default: %{}
      add :request_text, :text
      add :last_reply, :text
      add :quote_number, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:quote_sessions, [:ticket_id], name: "quote_sessions_unique_ticket_index")
  end

  def down do
    drop_if_exists unique_index(:quote_sessions, [:ticket_id],
                     name: "quote_sessions_unique_ticket_index"
                   )

    drop table(:quote_sessions)
  end
end
