defmodule TragarAi.Repo.Migrations.AddInteractionSearchStrategy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      add :search_strategy, :text
    end
  end

  def down do
    alter table(:interactions) do
      remove :search_strategy
    end
  end
end
