defmodule TragarAi.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tool_calls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tool, :text, null: false
      add :transport, :text, null: false
      add :client, :text
      add :arguments, :map, default: %{}
      add :outcome, :text, null: false, default: "ok"
      add :duration_ms, :bigint
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:shipments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :waybill_number, :text, null: false
      add :account_reference, :text
      add :shipper_reference, :text
      add :service_type, :text
      add :status_code, :text
      add :status_description, :text
      add :consignor_name, :text
      add :consignee_name, :text
      add :tracking_events, {:array, :map}, default: []
      add :raw, :map, default: %{}
      add :view, :map, default: %{}
      add :tracked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:shipments, [:waybill_number], name: "shipments_unique_waybill_index")

    create table(:api_clients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false, default: "account"
      add :status, :text, null: false, default: "pending"
      add :label, :text
      add :email, :citext
      add :account_reference, :text
      add :token_hash, :text
      add :activation_token_hash, :text
      add :activation_expires_at, :utc_datetime_usec
      add :activated_at, :utc_datetime_usec
      add :last_used_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid
    end

    create unique_index(:api_clients, [:token_hash], name: "api_clients_unique_token_hash_index")

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:api_clients) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "api_clients_account_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:accounts) do
      add :account_reference, :text, null: false
      add :email, :citext
      add :name, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts, [:account_reference], name: "accounts_unique_reference_index")
  end

  def down do
    drop_if_exists unique_index(:accounts, [:account_reference],
                     name: "accounts_unique_reference_index"
                   )

    alter table(:accounts) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :name
      remove :email
      remove :account_reference
    end

    drop constraint(:api_clients, "api_clients_account_id_fkey")

    alter table(:api_clients) do
      modify :account_id, :uuid
    end

    drop table(:accounts)

    drop_if_exists unique_index(:api_clients, [:token_hash],
                     name: "api_clients_unique_token_hash_index"
                   )

    drop table(:api_clients)

    drop_if_exists unique_index(:shipments, [:waybill_number],
                     name: "shipments_unique_waybill_index"
                   )

    drop table(:shipments)

    drop table(:tool_calls)
  end
end
