defmodule TragarAi.Repo.Migrations.DomainResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shipments) do
      remove :raw
      remove :tracking_events
      remove :consignee_name
      remove :consignor_name
      remove :status_description
      remove :shipper_reference
      add :status, :text
      add :consignor, :text
      add :consignee, :text
      add :events, {:array, :map}, default: []
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
    end

    alter table(:quotes) do
      remove :raw
      remove :consignee_name
      remove :consignor_name
      remove :status_description
      add :status, :text
      add :consignor, :text
      add :consignee, :text
      add :sources, {:array, :text}, default: []
      add :source_data, :map, default: %{}
    end
  end

  def down do
    alter table(:quotes) do
      remove :source_data
      remove :sources
      remove :consignee
      remove :consignor
      remove :status
      add :status_description, :text
      add :consignor_name, :text
      add :consignee_name, :text
      add :raw, :map, default: %{}
    end

    alter table(:shipments) do
      remove :source_data
      remove :sources
      remove :events
      remove :consignee
      remove :consignor
      remove :status
      add :shipper_reference, :text
      add :status_description, :text
      add :consignor_name, :text
      add :consignee_name, :text
      add :tracking_events, {:array, :map}, default: []
      add :raw, :map, default: %{}
    end
  end
end
