defmodule TragarAi.Repo.Migrations.SourceRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vehicles) do
      remove :source_data
    end

    create table(:source_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entity_type, :text, null: false
      add :entity_key, :text, null: false
      add :source, :text, null: false
      add :external_id, :text
      add :data, :map, default: %{}
      add :raw, :map, default: %{}
      add :synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:source_records, [:entity_type, :entity_key, :source],
             name: "source_records_unique_link_index"
           )

    alter table(:customers) do
      remove :source_data
    end
  end

  def down do
    alter table(:customers) do
      add :source_data, :map, default: %{}
    end

    drop_if_exists unique_index(:source_records, [:entity_type, :entity_key, :source],
                     name: "source_records_unique_link_index"
                   )

    drop table(:source_records)

    alter table(:vehicles) do
      add :source_data, :map, default: %{}
    end
  end
end
