defmodule TragarAi.Accounts.ApiClient do
  @moduledoc """
  Binds an API key to a single account (or marks a trusted partner system).

    * `scope: :account` — a customer key, locked to `account_reference`. May only
      read shipments belonging to that account.
    * `scope: :partner` — a trusted system (e.g. the Freshdesk/Freddy
      integration). Used only to *request access* on a customer's behalf; not for
      reading customer data directly.

  Lifecycle: `:pending` (magic link sent) → `:active` (customer activated, key
  issued) → `:revoked`. Only SHA-256 hashes of the API key and the activation
  token are stored.
  """

  use Ash.Resource,
    otp_app: :tragar_ai,
    domain: TragarAi.Accounts,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "api_clients"
    repo TragarAi.Repo

    references do
      reference :account, on_delete: :delete
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :scope, :atom,
      constraints: [one_of: [:account, :partner]],
      default: :account,
      allow_nil?: false

    attribute :status, :atom,
      constraints: [one_of: [:pending, :active, :revoked]],
      default: :pending,
      allow_nil?: false

    attribute :label, :string
    attribute :email, :ci_string, description: "Email the access was issued to."
    attribute :account_reference, :string, description: "Denormalized for fast scoping."

    attribute :token_hash, :string, description: "SHA-256 of the active API key."

    attribute :activation_token_hash, :string,
      description: "SHA-256 of the pending magic-link token."

    attribute :activation_expires_at, :utc_datetime_usec
    attribute :activated_at, :utc_datetime_usec
    attribute :last_used_at, :utc_datetime_usec
    attribute :revoked_at, :utc_datetime_usec

    timestamps()
  end

  relationships do
    belongs_to :account, TragarAi.Accounts.Account do
      attribute_type :uuid
      allow_nil? true
    end
  end

  identities do
    identity :unique_token_hash, [:token_hash], nils_distinct?: true
  end

  actions do
    defaults [:read, :destroy]

    # Step 1 of registration: create a pending client and stash the activation
    # token hash. The plaintext magic-link token is generated by the caller.
    create :request_access do
      accept [
        :account_id,
        :account_reference,
        :email,
        :label,
        :activation_token_hash,
        :activation_expires_at
      ]

      change set_attribute(:scope, :account)
      change set_attribute(:status, :pending)
    end

    # Step 2: customer clicked the link; store the issued key's hash + activate.
    update :activate do
      accept [:token_hash]
      require_atomic? false

      change set_attribute(:status, :active)
      change set_attribute(:activation_token_hash, nil)

      change fn changeset, _ ->
        Ash.Changeset.force_change_attribute(changeset, :activated_at, DateTime.utc_now())
      end
    end

    update :revoke do
      accept []
      require_atomic? false

      change set_attribute(:status, :revoked)
      change set_attribute(:token_hash, nil)

      change fn changeset, _ ->
        Ash.Changeset.force_change_attribute(changeset, :revoked_at, DateTime.utc_now())
      end
    end

    update :touch do
      accept []
      require_atomic? false

      change fn changeset, _ ->
        Ash.Changeset.force_change_attribute(changeset, :last_used_at, DateTime.utc_now())
      end
    end

    # Provision a trusted partner key directly (admin / mix task / seeds).
    create :create_partner do
      accept [:label, :token_hash]
      change set_attribute(:scope, :partner)
      change set_attribute(:status, :active)

      change fn changeset, _ ->
        Ash.Changeset.force_change_attribute(changeset, :activated_at, DateTime.utc_now())
      end
    end

    # Directly mint an active key (admin provisioning / seeds / tests),
    # bypassing the magic-link flow. The caller supplies the key's hash.
    create :provision do
      accept [:scope, :status, :account_id, :account_reference, :email, :label, :token_hash]
      change set_attribute(:status, :active)

      change fn changeset, _ ->
        Ash.Changeset.force_change_attribute(changeset, :activated_at, DateTime.utc_now())
      end
    end

    read :active_by_token_hash do
      argument :token_hash, :string, allow_nil?: false
      get? true
      filter expr(token_hash == ^arg(:token_hash) and status == :active)
    end

    read :pending_by_activation_hash do
      argument :activation_token_hash, :string, allow_nil?: false
      get? true
      filter expr(activation_token_hash == ^arg(:activation_token_hash) and status == :pending)
    end
  end
end
